FIX: Bump sushi to latest version to re-enable auto-builder.
Build FHIR IG from /scratch/repo
(00:00.038 / 00:00.039, 97Mb)
API keys loaded from /etc/fhir-settings.json
(00:00.004 / 00:00.043, 97Mb)
Package Cache: /var/lib/.fhir/packages
(00:00.004 / 00:00.047, 97Mb)
Run Sushi on /scratch/repo
(00:00.013 / 00:00.061, 97Mb)
Sushi: npm WARN exec The following package was not found and will be
installed: fsh-sushi@3.15.0     (00:01.355 / 00:01.416, 105Mb)
Sushi: npm WARN deprecated inflight@1.0.6: This module is not supported,
and leaks memory. Do not use it. Check out lru-cache if you want a good
and tested way to coalesce async requests by a key value, which is much
more comprehensive and powerful. (00:02.369 / 00:03.786, 105Mb)
Sushi: npm WARN deprecated rimraf@2.6.3: Rimraf versions prior to v4 are
no longer supported         (00:00.045 / 00:03.831, 105Mb)
Sushi: npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no
longer supported             (00:00.078 / 00:03.910, 105Mb)
Sushi: info  Running SUSHI v3.15.0 (implements FHIR Shorthand
specification v3.0.0)                  (00:02.344 / 00:06.255, 105Mb)
Sushi: info  Arguments:
(00:00.000 / 00:06.256, 113Mb)
Sushi: info    --require-latest
(00:00.000 / 00:06.257, 113Mb)
Sushi: info    --out /scratch/repo
(00:00.000 / 00:06.257, 113Mb)
Sushi: info    /scratch/repo
(00:00.000 / 00:06.258, 113Mb)
Sushi: error Current SUSHI version (3.15.0) is not the latest version.
Upgrade to the latest version (3.15.1) or run SUSHI again without the
--require-latest flag. (00:01.269 / 00:07.528, 113Mb)
Sushi couldn't be run. Complete output from running Sushi :
(00:00.037 / 00:07.565, 113Mb)
Note: Check that Sushi is installed correctly ("npm install -g
fsh-sushi". On windows, get npm from https://www.npmjs.com/get-npm)
(00:00.000 / 00:07.566, 113Mb)
Exception: Process exited with an error: 1 (Exit value: 1)
(00:00.000 / 00:07.566, 113Mb)
Publishing Content Failed: Process exited with an error: 1 (Exit value:
1)                           (00:00.000 / 00:07.567, 113Mb)